"""initial schema

Revision ID: db0e594a4177
Revises: 
Create Date: 2026-05-04 10:02:33.815286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db0e594a4177'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indicators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name_he', sa.String(length=100), nullable=False),
    sa.Column('domain', sa.String(length=30), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('is_percentage', sa.Boolean(), nullable=False),
    sa.Column('higher_is_better', sa.Boolean(), nullable=True),
    sa.Column('cbs_column_variants', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('description_he', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('municipalities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('symbol_cbs', sa.String(length=10), nullable=True),
    sa.Column('municipality_type', sa.String(length=30), nullable=True),
    sa.Column('district', sa.String(length=30), nullable=True),
    sa.Column('region', sa.String(length=30), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('socioeconomic_cluster', sa.Integer(), nullable=True),
    sa.Column('name_aliases', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('symbol_cbs')
    )
    op.create_table('data_points',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('municipality_id', sa.Integer(), nullable=False),
    sa.Column('indicator_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('source_file', sa.String(length=100), nullable=True),
    sa.Column('sheet_name', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicators.id'], ),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('municipality_id', 'indicator_id', 'year', name='uq_data_point')
    )
    op.create_table('national_averages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('indicator_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('avg_value', sa.Float(), nullable=True),
    sa.Column('median_value', sa.Float(), nullable=True),
    sa.Column('percentile_25', sa.Float(), nullable=True),
    sa.Column('percentile_75', sa.Float(), nullable=True),
    sa.Column('district_values', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indicator_id', 'year', name='uq_national_average')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('national_averages')
    op.drop_table('data_points')
    op.drop_table('municipalities')
    op.drop_table('indicators')
    # ### end Alembic commands ###
